function [] = density()
% DENSITY  Update gas density from the ideal gas law (variable-density / low-Mach).
% Mirrors the supplied wc3/convdiff03.m density routine, but the thermodynamic
% reference pressure is now the EVOLVING chamber pressure P_chamber (not a fixed
% P_ATM):
%     rho = (1-relax_rho)*rho + relax_rho*(p + P_chamber)/(R_GAS*T)
% Here p is the small hydrodynamic (gauge) pressure that drives the flow, and
% P_chamber is the spatially-uniform THERMODYNAMIC pressure that pressurises the
% gas. P_chamber is advanced in run_grenade from the mass balance
% (gas generated by the burn  -  gas vented through the orifice): when generation
% outpaces venting, P_chamber rises, so rho rises here - that is the physical
% "gas made faster than it can escape" pressure buildup, now COUPLED into the
% flow instead of being a decoupled side calculation.
% Under-relaxation (relax_rho) is used because the density<->pressure<->velocity
% coupling is stiff, especially with the fast temperature change from combustion.

% constants
global NPI NPJ relax_rho R_GAS SMALL P_chamber
% variables
global rho p T

% Ideal-gas density at the current chamber pressure (low-Mach). P_chamber lags
% by one step (it is updated at the end of each step in run_grenade), which is
% fine for this gentle, under-relaxed coupling.
for I = 1:NPI+2
    for J = 2:NPJ+1
        if I == 1                 % p(1,J) doesn't exist; use the neighbour
            pcell = p(2,J);
        else
            pcell = p(I,J);
        end
        rho(I,J) = (1-relax_rho)*rho(I,J) ...
                 + relax_rho*(pcell + P_chamber)/(R_GAS*max(T(I,J),SMALL));
    end
end
end
