function [] = bound()
% Purpose: Specify boundary conditions for the grenade calculation.
%  - all casing walls: no slip; temperature equals the lumped casing
%    temperature (conducting, NOT adiabatic; see walltemp.m); zero
%    species flux (zero gradient);
%  - hole in the left wall (rows JH1..JH2): outflow. The outflow velocity
%    follows from global continuity: all gas generated by the reaction
%    (density storage change (rho_old-rho)/Dt summed over the domain)
%    must leave through the hole. This replaces the m_in/m_out outlet
%    correction of the base code, which has no inlet to balance here.

% constants
global NPI NPJ Dt SMALL UOUTMAX relax_uh JH1 JH2
% variables
global x_u y_v u v T mfu mox mk2 rho rho_old TwB TwT TwL TwR u_hole m_gen

% begin: globcont()========================================================
% gas generation rate = rate of change of mass stored in the domain
DV    = (x_u(4)-x_u(3))*(y_v(4)-y_v(3));   % uniform cell volume
m_gen = sum(sum(rho_old(2:NPI+1,2:NPJ+1) - rho(2:NPI+1,2:NPJ+1)))*DV/Dt;

den = 0.;
for J = JH1:JH2
    den = den + rho(1,J)*(y_v(J+1) - y_v(J)); % same face density as convect()
end
% Target velocity from global continuity, applied with under-relaxation:
% u_hole couples every cell's density to the boundary condition, so an
% unrelaxed update is a stiff feedback loop that oscillates against the
% clamp. Outflow may be large; inflow ("breathing" of the canister) is
% limited to a small value.
utar   = m_gen/max(den,SMALL);
utar   = min(max(utar,-2.),UOUTMAX);
u_hole = u_hole + relax_uh*(utar - u_hole);
% end: globcont()==========================================================

global DEBUGB
if ~isempty(DEBUGB) && DEBUGB
    fprintf('   [bound] m_gen=%10.4g  den=%10.4g  u_hole=%10.4g\n',m_gen,den,u_hole);
end

% left boundary: casing wall with the venting hole
for J = 1:NPJ+2
    if J >= JH1 && J <= JH2
        u(2,J) = -u_hole;      % outflow through the hole (negative x)
        T(1,J) = T(2,J);       % zero temperature gradient at the opening
    else
        u(2,J) = 0.;           % no slip at the casing
        T(1,J) = TwL(J);       % conducting casing temperature
    end
    u(1,J) = u(2,J);
end
v(1,JH1:JH2+1) = v(2,JH1:JH2+1);           % zero gradient across the hole
v(1,1:JH1-1)   = 0.;
v(1,JH2+2:NPJ+2) = 0.;

% right, bottom and top boundaries: solid casing (no slip)
u(NPI+2,1:NPJ+2) = 0.;
v(NPI+2,1:NPJ+2) = 0.;
v(1:NPI+2,1) = 0.;
v(1:NPI+2,2) = 0.;
v(1:NPI+2,NPJ+2) = 0.;
u(1:NPI+2,1) = 0.;
u(1:NPI+2,NPJ+2) = 0.;

% conducting casing temperatures (bottom/top/right)
T(NPI+2,1:NPJ+2) = TwR(1:NPJ+2);
T(1:NPI+2,1)     = TwB(1:NPI+2);
T(1:NPI+2,NPJ+2) = TwT(1:NPI+2);

% species: zero gradient on all boundaries (no flux into the walls,
% advective outflow at the hole)
mfu(1,:) = mfu(2,:);  mfu(NPI+2,:) = mfu(NPI+1,:);
mfu(:,1) = mfu(:,2);  mfu(:,NPJ+2) = mfu(:,NPJ+1);
mox(1,:) = mox(2,:);  mox(NPI+2,:) = mox(NPI+1,:);
mox(:,1) = mox(:,2);  mox(:,NPJ+2) = mox(:,NPJ+1);
mk2(1,:) = mk2(2,:);  mk2(NPI+2,:) = mk2(NPI+1,:);
mk2(:,1) = mk2(:,2);  mk2(:,NPJ+2) = mk2(:,NPJ+1);
end
